# a mybinder.org-ready environment for demoing jlab-enhanced-cell-toolbar
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jlab-enhanced-cell-toolbar-demo
#
name: jlab-enhanced-cell-toolbar-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.10.0
  - jupyterlab >=3.4.0,<4.0.0a0
  # labextension build dependencies
  - nodejs >=14,<17
  - pip
  - wheel
  # Dependencies
  - packaging
